### PR TITLE
pre-commit: test PR76458

### PR DESCRIPTION
**Pull request by dtcxzyw**
PR Link: https://github.com/llvm/llvm-project/pull/76458

### CODE REVIEW

**Comment by dtcxzyw** [comment]
Regression:
```
diff --git a/bench/proxygen/optimized/HTTPTransactionEgressSM.cpp.ll b/bench/proxygen/optimized/HTTPTransactionEgressSM.cpp.ll
index 94a76d09..b01dce6a 100644
--- a/bench/proxygen/optimized/HTTPTransactionEgressSM.cpp.ll
+++ b/bench/proxygen/optimized/HTTPTransactionEgressSM.cpp.ll
@@ -243,7 +243,13 @@ if.then.i.i:                                      ; preds = %entry
 
 _ZNSt6vectorISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE17_S_check_init_lenEmRKS7_.exit.i: ; preds = %entry
   %cmp.not.i.i = icmp eq i64 %__l.coerce1, 0
-  br i1 %cmp.not.i.i, label %invoke.cont, label %for.body.i.i.i.i.preheader.i
+  br i1 %cmp.not.i.i, label %_ZNSt12_Vector_baseISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE11_M_allocateEm.exit.thread.i, label %for.body.i.i.i.i.preheader.i
+
+_ZNSt12_Vector_baseISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE11_M_allocateEm.exit.thread.i: ; preds = %_ZNSt6vectorISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE17_S_check_init_lenEmRKS7_.exit.i
+  %add.ptr8.i = getelementptr inbounds i8, ptr null, i64 %add.ptr.i.idx
+  %_M_end_of_storage9.i = getelementptr inbounds %"struct.std::_Vector_base<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>, std::allocator<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>>>::_Vector_impl_data", ptr %this, i64 0, i32 2
+  store ptr %add.ptr8.i, ptr %_M_end_of_storage9.i, align 8
+  br label %invoke.cont
 
 for.body.i.i.i.i.preheader.i:                     ; preds = %_ZNSt6vectorISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE17_S_check_init_lenEmRKS7_.exit.i
   %call5.i.i.i.i2 = invoke noalias noundef nonnull ptr @_Znwm(i64 noundef %add.ptr.i.idx) #15
@@ -251,7 +257,7 @@ for.body.i.i.i.i.preheader.i:                     ; preds = %_ZNSt6vectorISt4pai
 
 call5.i.i.i.i.noexc:                              ; preds = %for.body.i.i.i.i.preheader.i
   store ptr %call5.i.i.i.i2, ptr %this, align 8
-  %add.ptr.i1 = getelementptr inbounds %"struct.std::pair.5", ptr %call5.i.i.i.i2, i64 %__l.coerce1
+  %add.ptr.i1 = getelementptr inbounds i8, ptr %call5.i.i.i.i2, i64 %add.ptr.i.idx
   %_M_end_of_storage.i = getelementptr inbounds %"struct.std::_Vector_base<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>, std::allocator<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>>>::_Vector_impl_data", ptr %this, i64 0, i32 2
   store ptr %add.ptr.i1, ptr %_M_end_of_storage.i, align 8
   %0 = add nsw i64 %add.ptr.i.idx, -3
@@ -262,8 +268,8 @@ call5.i.i.i.i.noexc:                              ; preds = %for.body.i.i.i.i.pr
   %scevgep.i = getelementptr i8, ptr %call5.i.i.i.i2, i64 %3
   br label %invoke.cont
 
-invoke.cont:                                      ; preds = %_ZNSt6vectorISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE17_S_check_init_lenEmRKS7_.exit.i, %call5.i.i.i.i.noexc
-  %__cur.0.lcssa.i.i.i.i.i = phi ptr [ %scevgep.i, %call5.i.i.i.i.noexc ], [ null, %_ZNSt6vectorISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE17_S_check_init_lenEmRKS7_.exit.i ]
+invoke.cont:                                      ; preds = %call5.i.i.i.i.noexc, %_ZNSt12_Vector_baseISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE11_M_allocateEm.exit.thread.i
+  %__cur.0.lcssa.i.i.i.i.i = phi ptr [ %scevgep.i, %call5.i.i.i.i.noexc ], [ null, %_ZNSt12_Vector_baseISt4pairIS0_IN8proxygen27HTTPTransactionEgressSMData5StateENS2_5EventEES3_ESaIS6_EE11_M_allocateEm.exit.thread.i ]
   %_M_finish.i = getelementptr inbounds %"struct.std::_Vector_base<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>, std::allocator<std::pair<std::pair<proxygen::HTTPTransactionEgressSMData::State, proxygen::HTTPTransactionEgressSMData::Event>, proxygen::HTTPTransactionEgressSMData::State>>>::_Vector_impl_data", ptr %this, i64 0, i32 1
   store ptr %__cur.0.lcssa.i.i.i.i.i, ptr %_M_finish.i, align 8
   ret void

```

**Comment by nikic** [comment]
@dtcxzyw It's possible to fold `getelementptr inbounds i8, ptr null, i64 %add.ptr.i.idx` to `null` (assuming this is not compiled with `-fno-delete-null-pointer-checks`).

**Comment by dtcxzyw** [comment]
> @dtcxzyw It's possible to fold `getelementptr inbounds i8, ptr null, i64 %add.ptr.i.idx` to `null` (assuming this is not compiled with `-fno-delete-null-pointer-checks`).

Alive2: https://alive2.llvm.org/ce/z/Zy_4Dz
My concern is that it would breaks some incorrect `offsetof` idioms like `#define offsetof(st, m) ((size_t)&(((st *)0)->m))`, which is UB according to the C/C++ standard.
Example: https://godbolt.org/z/PvT57z895

I will post a patch later.

**Comment by nikic** [comment]
@dtcxzyw We could avoid doing the transform if the offset is also constant. Or change clang frontend to not emit `inbounds` for this specific pattern. I agree that it would be best not to break it.

**Comment by dtcxzyw** [comment]
A possible miscompilation after simplifying `gep inbounds null, idx -> null`:
https://godbolt.org/z/Gshj9rz6e
```
#include <vector>

std::vector<std::vector<int>> test(std::vector<int> y) {
	std::vector<std::vector<int>> x;
	x.push_back(y);
	return x;
}
```

diff:
```
148,151c148
<   %add.ptr.i.i.i.i.i70 = getelementptr inbounds i32, ptr null, i64 %sub.ptr.div.i.i.i.i
<   %_M_end_of_storage.i.i.i.i.i71 = getelementptr inbounds %"struct.std::_Vector_base<int, std::allocator<int>>::_Vector_impl_data", ptr %add.ptr, i64 0, i32 2
<   tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %add.ptr, i8 0, i64 16, i1 false)
<   store ptr %add.ptr.i.i.i.i.i70, ptr %_M_end_of_storage.i.i.i.i.i71, align 8, !tbaa !16
---
>   tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(24) %add.ptr, i8 0, i64 24, i1 false)
```
But this BB seems to be unreachable.

**Pull request closed without merging**
