### PR TITLE
pre-commit: test PR76295

### PR DESCRIPTION
**Pull request by dtcxzyw**
PR Link: https://github.com/llvm/llvm-project/pull/76295

### CODE REVIEW

**Comment by nikic** [comment]
bench/abseil-cpp/optimized/cord_rep_btree.cc.ll looks like a regression.

**Comment by dtcxzyw** [comment]
> bench/abseil-cpp/optimized/cord_rep_btree.cc.ll looks like a regression.

Context:
```

%retval.sroa.5.0.i.i.i = phi i32 [ 0, %if.then.i.i.i ], [ 0, %if.then.i.i.i.i ], [ 1, %if.else.i.i.i ], [ 1, %for.body.i.i.i ]
%retval.sroa.3.0.i = phi i32 [ 0, %if.then6 ], [ 1, %cond.false.i ], [ 1, %for.body.i.i ]

do.body.i.i:
%result.sroa.7.0.i.i = phi i32 [ %retval.sroa.3.0.i, %do.body.preheader.i.i ], [ %result.sroa.7.1.i.i, %do.cond.i.i ]
switch i32 %result.sroa.7.0.i.i, label %do.cond.i.i [
  i32 2, label %sw.bb.i.i
  i32 1, label %sw.bb4.i.i
  i32 0, label %sw.bb13.i.i
]

%sw.bb.i.i: ; preds = %do.body.i.i
%28 = extractvalue { ptr, i32 } %call.i.i, 1 ; range: [0, 3)

%do.cond.i.i:
%result.sroa.7.1.i.i = phi i32 [ %result.sroa.7.0.i.i, %do.body.i.i ], 
[ %retval.sroa.5.0.i.i.i, %_ZN4absl13cord_internal12CordRepBtree7SetEdgeILNS1_8EdgeTypeE0EEENS1_8OpResultEbPNS0_7CordRepEm.exit.i.i ], 
[ %28, %sw.bb.i.i ]

```

A minimal reproduction:
```
define i32 @test(i32 %a, i32 %b) {
entry:
  %c = urem i32 %a, 2
  br label %body
body:
  %phi = phi i32 [%c, %entry], [%phi.i, %latch]
  switch i32 %phi, label %latch [
    i32 2, label %bb2
    i32 1, label %bb1
    i32 0, label %bb1
  ]
bb1:
  call void @side_effect()
  %val1 = urem i32 %b, 2
  br label %latch
bb2:
  %val2 = call i32 @call()
  br label %latch
latch:
  %phi.i = phi i32 [%phi, %body], [%val1, %bb1], [%val2, %bb2]
  %cond = call i1 @use()
  br i1 %cond, label %body, label %exit
exit:
  ret i32 0
}

declare i32 @call()
declare i1 @use()
declare void @side_effect()
```
I cannot reproduce the regression. Does it reach the maximum recursion depth when computing the constant range?

**Comment by dtcxzyw** [comment]
> bench/abseil-cpp/optimized/cord_rep_btree.cc.ll looks like a regression.

Reproduction: https://godbolt.org/z/197j7r3G5
```
define dso_local void @test() local_unnamed_addr {
entry:
  %0 = tail call i8 @geti8()
  %conv.i = zext i8 %0 to i32
  %cmp19.i.not = tail call i1 @geti1()
  br i1 %cmp19.i.not, label %while.end.i.thread, label %exit2

while.end.i.thread:                               ; preds = %entry
  %1 = tail call i1 @geti1()
  %2 = zext i1 %1 to i32
  br label %exit2

exit2:                                            ; preds = %while.end.i.thread, %entry
  %cmp.i12.i4 = phi i32 [ %2, %while.end.i.thread ], [ 0, %entry ]
  %cmp = tail call i1 @geti1()
  br i1 %cmp, label %if.then6, label %if.end.i.i

if.then6:                                         ; preds = %exit2
  %cmp.i32 = icmp ugt i32 %cmp.i12.i4, %conv.i
  br i1 %cmp.i32, label %exit, label %cond.false.i

cond.false.i:                                     ; preds = %if.then6
  %cmp.not6.i.i = tail call i1 @geti1()
  br i1 %cmp.not6.i.i, label %exit, label %for.body.preheader.i.i

for.body.preheader.i.i:                           ; preds = %cond.false.i
  %cmp.not.i.i = tail call i1 @geti1()
  br label %exit

exit:                                             ; preds = %for.body.preheader.i.i, %cond.false.i, %if.then6
  %retval.sroa.3.0.i = phi i32 [ 0, %if.then6 ], [ 1, %cond.false.i ], [ 1, %for.body.preheader.i.i ]
  br i1 %cmp19.i.not, label %if.end.i.i, label %do.body.i.i

do.body.i.i:                                      ; preds = %exit, %do.cond.i.i
  %result.sroa.7.0.i.i = phi i32 [ %result.sroa.7.1.i.i, %do.cond.i.i ], [ %retval.sroa.3.0.i, %exit ]
  switch i32 %result.sroa.7.0.i.i, label %do.cond.i.i [
    i32 2, label %sw.bb.i.i
    i32 1, label %if.end.i.i
    i32 0, label %if.end.i.i
  ]

sw.bb.i.i:                                        ; preds = %do.body.i.i
  %3 = tail call i32 @geti32()
  br label %do.cond.i.i

do.cond.i.i:                                      ; preds = %sw.bb.i.i, %do.body.i.i
  %result.sroa.7.1.i.i = phi i32 [ %result.sroa.7.0.i.i, %do.body.i.i ], [ %3, %sw.bb.i.i ]
  %cmp22.i.i = tail call i1 @geti1()
  br i1 %cmp22.i.i, label %do.body.i.i, label %if.end.i.i, !llvm.loop !5

if.end.i.i:                                       ; preds = %do.cond.i.i, %do.body.i.i, %do.body.i.i, %exit, %exit2
  ret void
}

declare i8 @geti8() local_unnamed_addr

declare i32 @geti32() local_unnamed_addr

declare i1 @geti1() local_unnamed_addr

!llvm.module.flags = !{!0, !1, !2, !3, !4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
```
`%result.sroa.7.0.i.i` was marked as `overdefined` because we reached the max widen steps.

**Comment by dtcxzyw** [comment]
> > bench/abseil-cpp/optimized/cord_rep_btree.cc.ll looks like a regression.
> 
> Reproduction: https://godbolt.org/z/197j7r3G5
> 
> ```
> define dso_local void @test() local_unnamed_addr {
> entry:
>   %0 = tail call i8 @geti8()
>   %conv.i = zext i8 %0 to i32
>   %cmp19.i.not = tail call i1 @geti1()
>   br i1 %cmp19.i.not, label %while.end.i.thread, label %exit2
> 
> while.end.i.thread:                               ; preds = %entry
>   %1 = tail call i1 @geti1()
>   %2 = zext i1 %1 to i32
>   br label %exit2
> 
> exit2:                                            ; preds = %while.end.i.thread, %entry
>   %cmp.i12.i4 = phi i32 [ %2, %while.end.i.thread ], [ 0, %entry ]
>   %cmp = tail call i1 @geti1()
>   br i1 %cmp, label %if.then6, label %if.end.i.i
> 
> if.then6:                                         ; preds = %exit2
>   %cmp.i32 = icmp ugt i32 %cmp.i12.i4, %conv.i
>   br i1 %cmp.i32, label %exit, label %cond.false.i
> 
> cond.false.i:                                     ; preds = %if.then6
>   %cmp.not6.i.i = tail call i1 @geti1()
>   br i1 %cmp.not6.i.i, label %exit, label %for.body.preheader.i.i
> 
> for.body.preheader.i.i:                           ; preds = %cond.false.i
>   %cmp.not.i.i = tail call i1 @geti1()
>   br label %exit
> 
> exit:                                             ; preds = %for.body.preheader.i.i, %cond.false.i, %if.then6
>   %retval.sroa.3.0.i = phi i32 [ 0, %if.then6 ], [ 1, %cond.false.i ], [ 1, %for.body.preheader.i.i ]
>   br i1 %cmp19.i.not, label %if.end.i.i, label %do.body.i.i
> 
> do.body.i.i:                                      ; preds = %exit, %do.cond.i.i
>   %result.sroa.7.0.i.i = phi i32 [ %result.sroa.7.1.i.i, %do.cond.i.i ], [ %retval.sroa.3.0.i, %exit ]
>   switch i32 %result.sroa.7.0.i.i, label %do.cond.i.i [
>     i32 2, label %sw.bb.i.i
>     i32 1, label %if.end.i.i
>     i32 0, label %if.end.i.i
>   ]
> 
> sw.bb.i.i:                                        ; preds = %do.body.i.i
>   %3 = tail call i32 @geti32()
>   br label %do.cond.i.i
> 
> do.cond.i.i:                                      ; preds = %sw.bb.i.i, %do.body.i.i
>   %result.sroa.7.1.i.i = phi i32 [ %result.sroa.7.0.i.i, %do.body.i.i ], [ %3, %sw.bb.i.i ]
>   %cmp22.i.i = tail call i1 @geti1()
>   br i1 %cmp22.i.i, label %do.body.i.i, label %if.end.i.i, !llvm.loop !5
> 
> if.end.i.i:                                       ; preds = %do.cond.i.i, %do.body.i.i, %do.body.i.i, %exit, %exit2
>   ret void
> }
> 
> declare i8 @geti8() local_unnamed_addr
> 
> declare i32 @geti32() local_unnamed_addr
> 
> declare i1 @geti1() local_unnamed_addr
> 
> !llvm.module.flags = !{!0, !1, !2, !3, !4}
> 
> !0 = !{i32 1, !"wchar_size", i32 4}
> !1 = !{i32 8, !"PIC Level", i32 2}
> !2 = !{i32 7, !"PIE Level", i32 2}
> !3 = !{i32 7, !"uwtable", i32 2}
> !4 = !{i32 7, !"frame-pointer", i32 2}
> !5 = distinct !{!5, !6}
> !6 = !{!"llvm.loop.mustprogress"}
> ```
> 
> `%result.sroa.7.0.i.i` was marked as `overdefined` because we reached the max widen steps.

I will post a patch later.

**Pull request closed without merging**
